# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9425bee2c74c4677f6abe6ceb9803d70db531636c2859d8f8047b8b524ba085becbccf4b01334109b943818b1f58c99df551786a408db954686e52818fb897aa

test:
  secret_key_base: 3cdab544e4203bf9454b5e7e4bac29861dca629caff36ccb325343b2d7148fd1d9490c3cf9dea9d2926bfcf1bdc62646133f7ad401d70fdebb8040e6b6efb62d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 9425bee2c74c4677f6abe6ceb9803d70db531636c2859d8f8047b8b524ba085becbccf4b01334109b943818b1f58c99df551786a408db954686e52818fb897ab
