# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe0e5a3b1693d98c3ddf115efbd1eab8b9881f85bb06627124043327839325283257c65f7cdf42bb7465a4b3369887d4d2e21c38543dbdc17dc9ce586ef4156e

test:
  secret_key_base: 569237c43609bdd374371df37d8abb3ceb5d6dc6086eb142a6707bdb1c7e848ca0f2e1f12db03cac9c9eaab6db71a49e8110b2450764f17d348995868db6acaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
